### ISSUE TITLE
ios error

### ISSUE THREAD

**Issue by flutter-painter** [tolotrasamuel/account_picker#1]
Great pub,
Anyway to circumvent this on ios ?
No podspec found for `account_picker` in `.symlinks/plugins/account_picker/ios`

**Comment by tolotrasamuel** [comment]
Unfortunately, ios is not supported yet. I am waiting for someone to send a
PR. Because I don't even have a Mac book. Never built an IoS app before.
If you find a solution, feel free to update this thread

**Comment by 926** [comment]
Haven't built one yet either,
Yet, this issue is not about ios support,
It is about not blocking the app from building on ios,
I encountered a similar issue with blue thermal plugin,
Though it does not work on iphone, the runner still builds.
I'll dig the following snippet,

```pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    if s.name == 'YOUR_POD_NAME_HERE'
      s.swift_version = '4.2'
    end
  end
end ```

**Comment by tolotrasamuel** [comment]
Have you tried if(Platform.isIos) // ignore the plugin

Or if I am understanding correctly, this happens during build time.

**Comment by pierre-gancel** [comment]
It happens during build time

**Comment by pierre-gancel** [comment]
simply copy paste the snipper in the build and remove pub from .yaml

**Comment by Jai05-techie** [comment]
Hi, facing same issue in iOS any workaround ?

**Comment by pierre-gancel** [comment]
remove the plugin from the .yaml and paste this in your code if device is android
I don't know if this also works on ios,
if there is a similar method, please share

``` dart
Future<List> getEmailFromMethodChannel() async {
  const MethodChannel _channel = const MethodChannel('account_picker');
  final List<dynamic> emailResult =
      await _channel.invokeMethod('requestEmailHint');
  if (emailResult != null) {
    // [0] email
    // [1] type of account
    return [emailResult[0], emailResult[1]];
  } else {
    return null;
  }
}

Future<String> getPhoneFromMethodChannel() async {
  const MethodChannel _channel = const MethodChannel('account_picker');
  final String phone = await _channel.invokeMethod('requestPhoneHint');
  return phone;
}
```

**Comment by pierre-gancel** [comment]
mea culpa this does not work
I had a look at https://flutter.dev/docs/development/platform-integration/platform-channels#step-4-add-an-ios-platform-specific-implementation

will see if I can PR with ios
