### ISSUE TITLE
PhoneHint is not compatible with Android S and above.

### ISSUE THREAD

**Issue by Gouravdeep** [tolotrasamuel/account_picker#8]
Please check below issue:

D/ContentValues(14201): Account Picker on Activity Result phone hint
D/ContentValues(14201): 711012
E/MethodChannel#account_picker(14201): Failed to handle method call
E/MethodChannel#account_picker(14201): java.lang.IllegalArgumentException: com.example.taxi_app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MethodChannel#account_picker(14201): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by almendezl** [comment]
Did you find a solution for this?

**Comment by VasukiBhava** [comment]
I'm also experiencing the issue on Android 14.

**Comment by tolotrasamuel** [comment]
Should be fixed with 2.2.0
